### ISSUE TITLE
[REQUEST] iOS 12 deprecations

### ISSUE THREAD

**Issue by nickdnk** [star-micronics/StarXpand-SDK-iOS#20]
## Is your feature request related to a problem? Please describe.

Your deprecation for `async` starts at iOS 12 and obsoletes at iOS 13. This means that users targeting 12.0 have no option to resolve these deprecations, as you've also explained in the warning. It also means you **force** people on iOS 13 to use async. Why? That's not how it's meant to work.

## Describe the solution you'd like

Please change the deprecation logic to deprecate at 13, not 12, and only obsolete if actually **required**. There is no reason I can think of why the non-async/legacy code cannot run if your target is iOS 13, so you can easily do this without breaking anything at all. Anyone targeting iOS 13 will then be told that they should change their code -- and they will be able to. If this is incorrect, please explain why, because it makes no sense to me.

## Describe alternatives you've considered
n/a

## Additional context
n/a

**Comment by cumanzor** [comment]
I think a bigger issue with this right now is the inconsistency. For example, I can call `StarPrinter.close() {}` on iOS13+ and the compiler is not throwing any warnings (as of Xcode 15 at least). However, during runtime, the call is not doing anything at all. 

This lead me to hours of troubleshooting and debugging only to realize the closure based call isn't doing anything at all. Which in turn makes me think the decision of using this deprecation logic may be related to their internal implementation.

**Comment by Tatsuki-Yamamoto2731** [comment]
@nickdnk @cumanzor  Sorry for the late response.
Since we want to provide APIs that use newer mechanisms, we have added support for methods that use async/await in iOS13/14.
On the other hand, in Swift, the old API and the new API can do the same things, and to avoid confusing users about which one to use, we have discontinued the old API. This will cause inconvenience to users who were already using the old API, but we appreciate your understanding.
