### ISSUE TITLE
Choosing between StarPRNT SDK and StarXpand SDK

### ISSUE THREAD

**Issue by mortenbekditlevsen** [star-micronics/StarXpand-SDK-iOS#23]
## Description
When looking for an iOS SDK on the homepage of Star, we are directed to the StarXpand SDK. 
This leads me to think that this is the recommended SDK to use.
We switched to this, and are generally happy about the switch (except the failure to detect a printer (TSP650II) that previously detected just fine using StarPRNT - I added a bug report for this).
But I recently noticed that both SDKs appear to get updates.

So I am just wondering: 
What is the recommended SDK to use? 
What are the main differences in what they support?
Where can I read about these recommendations?

**Comment by cschembor-cf** [comment]
I am also curious about this. Is the StarXpand SDK recommended over the StarPRNT SDK going forward?

**Comment by mezaniella** [comment]
I have an app in MAUI. And I don't know whether to make StarXpand or StarPRNT bindings. Which will be better in the future?

**Comment by cschembor-cf** [comment]
Hi @bandit-ibayashi , could we get a clarification here on which SDK to use going forward?

**Comment by Tatsuki-Yamamoto2731** [comment]
If you are going to introduce STAR's library newly, we recommend StarXpand SDK. This is because StarXpand is a new SDK and STAR will implement new features more aggressively in StarXpand SDK than in StarPRNT SDK. 
However, we know that many people are already using StarPRNT SDK, so we will continue to update StarPRNT SDK as well.
About StarXpand SDK, we described on  [this page](https://star-m.jp/eng/products/s_print/si_software/index.html#section-1).
